name: Question 作成用のテンプレート
description: Question 作成用のテンプレート
title: "[Question]: "
labels: "question"
body:
  - type: textarea
    attributes:
      label: 機能名
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 確認内容
    validations:
      required: true